maps = {
    "Small": ["SFFH", "FFFF", "FHFF", "FFFG"],
    "Medium": [
        "SFFFHFFH",
        "FFHFFFFH",
        "FFFFFFFF",
        "HHFFFFFF",
        "FFFHFFFF",
        "FFHFFHFF",
        "FHFFHFFF",
        "FFFFFFFG",
    ],
    "Large": [
        "SFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFHFFF",
        "FFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFG",
    ],
}
